print ("Roberts Rubins")
print ("Luize Veze")
print ("Katrina Vevere")

print ("Čeks Ikea")
print (" Īpašības")
print ("x2 grāmatplaukts 199.00 Euro")
print ("lampa 25.99 Euro")
print (" Metodes")
print ("pieskaitīt x2 grāmatplaukts 199.00 Euro")
print ("pieskaitīt lampa 25.99 Euro")
print ("summa 423.99 Euro")