print ("Roberts Rubins")
print ("Luize Veze")
print ("Katrina Vevere")

print ("Čeks Ikea")
print (" Īpašības")
print ("x2 grāmatplaukts")
print ("lampa")
print (" Metodes")
print ("pieskaitīt lampa")
print ("pieskaitīt x2 grāmatplaukts")
